pipeline {
    agent any

    stages {
        stage('git repo & clean') {
            steps {
                bat 'rmdir /s /q spring-boot-jenkins'
                bat 'git clone https://github.com/tulip2201/spring-boot-jenkins.git'
                bat 'mvn clean -f spring-boot-jenkins/springboot-jenkins-test'
            }
        }
        stage('install') {
            steps {
                bat 'mvn install -f spring-boot-jenkins/springboot-jenkins-test'
            }
        }
        stage('test') {
            steps {
                bat 'mvn test -f spring-boot-jenkins/springboot-jenkins-test'
            }
        }
        stage('package') {
            steps {
                bat 'mvn package -f spring-boot-jenkins/springboot-jenkins-test'
            }
        }
    }
}
